version: "3.9"

services:
  db:
    image: postgres:16
    container_name: messaging_app_db
    environment:
      POSTGRES_DB: messaging_app
      POSTGRES_USER: messaging_user
      POSTGRES_PASSWORD: messaging_password
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
